**Parte 1 — Preparação do ambiente**

In [1]:
import pandas as pd

In [8]:
df = pd.read_excel('qualidade_ar_brasil.xlsx')

Parte 2 — Inspeção inicial do **dataset**

1. Quantas medições existem no dataset? 800 medições
2. Quantas cidades estão presentes na base? 10 cidades
3. Quais colunas representam poluentes atmosféricos? pm25,pm10,no2,o3
4. Existem valores ausentes no dataset? não

In [11]:
df.shape

(800, 11)

In [12]:
df.head()

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
0,2025-01-01,Brasília,DF,33.7,60.9,44.6,2026-08-31 00:00:00,2026-05-25 00:00:00,57.8,61.7,Moderado
1,2025-01-01,Curitiba,PR,2026-07-25 00:00:00,2026-01-22 00:00:00,2026-04-29 00:00:00,40.0,2026-01-17 00:00:00,77.4,43.4,Moderado
2,2025-01-01,Salvador,BA,2026-08-18 00:00:00,2026-06-27 00:00:00,29.2,60.2,2026-03-29 00:00:00,78.0,47.5,Moderado
3,2025-01-02,Curitiba,PR,2026-04-12 00:00:00,41.1,20.0,32.6,2026-03-20 00:00:00,85.7,35.8,Bom
4,2025-01-03,Belo Horizonte,MG,32.0,57.3,36.4,2026-05-23 00:00:00,2026-03-26 00:00:00,74.6,54.1,Moderado

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data                 800 non-null    datetime64[ns]
 1   cidade               800 non-null    object
 2   estado               800 non-null    object
 3   pm25                 800 non-null    object
 4   pm10                 800 non-null    object
 5   no2                  800 non-null    object
 6   o3                   800 non-null    object
 7   temperatura          800 non-null    object
 8   umidade              800 non-null    float64
 9   indice_qualidade_ar  800 non-null    object
 10  nivel_alerta         800 non-null    object
dtypes: datetime64[ns](1), float64(1), object(9)
memory usage: 68.9+ KB

In [14]:
df.describe()

                      data     umidade
count                  800  800.000000
mean   2025-07-07 07:46:12   74.918750
min    2025-01-01 00:00:00   47.300000
25%    2025-03-31 18:00:00   69.275000
50%    2025-07-11 12:00:00   76.250000
75%    2025-10-11 06:00:00   81.425000
max    2025-12-31 00:00:00   96.000000
std                    NaN    9.492972

In [15]:
df.isnull().sum()

data                   0
cidade                 0
estado                 0
pm25                   0
pm10                   0
no2                    0
o3                     0
temperatura            0
umidade                0
indice_qualidade_ar    0
nivel_alerta           0
dtype: int64

Parte 3 — Análise por **cidade**

1. Qual cidade apresenta maior média de PM2.5? São Paulo
2. Qual cidade apresenta maior média de NO2? São Paulo
3. Existe alguma cidade com níveis consistentemente mais altos de poluentes? Sim

In [16]:
df['cidade'].unique()

array(['Brasília', 'Curitiba', 'Salvador', 'Belo Horizonte', 'Recife',
       'Fortaleza', 'Rio de Janeiro', 'Porto Alegre', 'Manaus',
       'São Paulo'], dtype=object)

In [22]:
colunas = ['pm25', 'pm10', 'no2', 'o3']
for col in colunas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

resultado = df.groupby('cidade')[colunas].mean()
resultado

                     pm25       pm10        no2         o3
cidade
Belo Horizonte  34.267647  49.552055  33.457143  36.051282
Brasília        38.811905  59.900000  35.472917  36.536207
Curitiba        33.591667  46.951948  31.417143  33.360870
Fortaleza       26.770833  46.976389  29.917647  37.511864
Manaus          32.513333  47.975949  27.718750  36.109302
Porto Alegre    33.862069  49.186567  34.555556  35.584615
Recife          29.860000  44.292857  30.147059  37.745833
Rio de Janeiro  34.200000  45.905634  36.477778  42.703077
Salvador        25.928571  44.019298  28.209524  38.898000
São Paulo       39.007895  57.583607  44.345833  39.939535

**Parte 4 — Análise do índice de qualidade do ar**:

1. Qual cidade apresenta pior qualidade média do ar? São Paulo
2. Qual cidade apresenta melhor qualidade do ar? Salvador

In [23]:
df['indice_qualidade_ar'] = pd.to_numeric(df['indice_qualidade_ar'], errors='coerce')
resultado = df.groupby('cidade')['indice_qualidade_ar'].mean().sort_values(ascending=False)
resultado

cidade
São Paulo         59.345312
Brasília          54.955172
Rio de Janeiro    50.870732
Belo Horizonte    48.344156
Porto Alegre      47.148571
Manaus            45.256098
Fortaleza         45.010256
Curitiba          44.359140
Recife            43.675610
Salvador          42.481579
Name: indice_qualidade_ar, dtype: float64

**Parte 5 — Filtragem por nível de alerta**
1. Quantos registros possuem alerta crítico? 14
2. Em quais cidades eles ocorrem com maior frequência?São Paulo concentra a maioria, com 8 dos 14 registros "Ruim". O restante se distribui entre Brasília, Rio de Janeiro, Belo Horizonte e Manaus

In [24]:
df_alerta = df[df['nivel_alerta'].isin(['Ruim','Muito Ruim'])]
df_alerta.head()

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
235,2025-04-20,São Paulo,SP,33.7,73.7,57.2,34.3,2026-09-25 00:00:00,61.1,70.8,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,2026-01-28 00:00:00,78.9,72.7,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,NaN,36.2,2026-07-31 00:00:00,74.9,71.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,2026-06-28 00:00:00,51.0,73.5,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim

**Parte 6 — Ranking dos dias mais críticos**

1. Qual foi o pior dia registrado? 19/08/2025
2. Em qual cidade ocorreu? São Paulo
3. Quais poluentes estavam mais altos nesse dia? PM10,PM2.5,NO2,O3

In [25]:
df.sort_values('indice_qualidade_ar', ascending=False).head(10)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,2026-03-20 00:00:00,80.3,86.3,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,2026-02-25 00:00:00,76.3,84.3,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,2026-02-21 00:00:00,74.7,76.5,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,NaN,2026-06-21 00:00:00,68.0,76.1,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,2026-08-23 00:00:00,62.5,73.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,2026-06-28 00:00:00,51.0,73.5,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,2026-01-28 00:00:00,78.9,72.7,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,2026-04-22 00:00:00,79.9,71.8,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,NaN,36.2,2026-07-31 00:00:00,74.9,71.6,Ruim

**Parte 7 — Análise temporal**

1. Em quais meses a qualidade do ar tende a ser pior?Junho e Julho
2. Existe algum padrão sazonal?A qualidade do ar piora no outono/inverno e melhora no verão

In [26]:
df['data'] = pd.to_datetime(df['data'], errors='coerce')
df['mes'] = df['data'].dt.month
df['indice_qualidade_ar'] = pd.to_numeric(df['indice_qualidade_ar'], errors='coerce')
resultado = df.groupby('mes')['indice_qualidade_ar'].mean()
resultado

mes
1     45.075000
2     43.909615
3     46.675949
4     47.559259
5     47.352381
6     52.881034
7     51.293443
8     49.640000
9     49.923333
10    48.105195
11    47.351471
12    45.829333
Name: indice_qualidade_ar, dtype: float64

**Parte 8 — Correlação entre variáveis**

1. Existe correlação entre temperatura e poluição?Temperatura × PM2.5: -0,21
Temperatura × NO2: -0,19
Temperatura × O3: +0,13
Temperatura × Índice geral: -0,12
2. Quais poluentes parecem mais relacionados entre si?PM10 × NO2: 0,20
PM2.5 × PM10: 0,18
O3 com os demais: praticamente zero

In [28]:
colunas = ['temperatura', 'pm25', 'pm10', 'no2', 'o3']
for col in colunas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

resultado = df[colunas].corr()
resultado

             temperatura      pm25      pm10       no2        o3
temperatura     1.000000 -0.288850 -0.221902 -0.250062  0.069031
pm25           -0.288850  1.000000  0.180818  0.072963 -0.002545
pm10           -0.221902  0.180818  1.000000  0.202078  0.000558
no2            -0.250062  0.072963  0.202078  1.000000  0.122175
o3              0.069031 -0.002545  0.000558  0.122175  1.000000

**Desafio Final — Relatório para o Ministério**

1. Qual cidade apresenta pior qualidade média do ar?  São Paulo
2. Quais poluentes são mais críticos? PM2.5 e PM10
3. Existem meses mais problemáticos? Sim, junho e julho
4. Quais cidades deveriam receber maior atenção das autoridades ambientais? São Paulo, Rio de Janeiro e Brasília